### ISSUE TITLE
A suggestion of linkage

### ISSUE THREAD

**Issue by iamsoNewBee** [connor135246/Campfire-Backport#23]
When the mod is loaded with EnviroMine or Tough As Nails，the campfire will raise  player`s body temperture.

**Comment by KibaTheBarbarian** [comment]
you can add it to EnviroMine and Tough As Nails is not in 1.7.10 and use this ver https://www.curseforge.com/minecraft/mc-mods/enviromine-for-galaxy-odyssey it's the most up-to-date

**Comment by iamsoNewBee** [comment]
> 

Yes Tough As Nails is not in 1.7.10 lol

**Comment by connor135246** [comment]
EnviroMine lets you add temperature to any block in their config.

First, launch the game with EnviroMine and Campfire Backport installed. Click the Mods button on the title screen, then find EnviroMine and click on Config. Then go to `Profile Settings` -> `default_Settings.cfg` -> `Config` and set `Generate Blank Configs` to `true`. When you click done, EnviroMine will generate configs for all of your mods and set the option back to false. It can take a while if you have a lot of mods.
Now you can go back into the config and set campfires to raise your temperature. Go to `Custom Configs` -> `campfirebackport.cfg` -> `blocks`. I'd recommend setting the campfires to the same values as torches. That would be `Enable Temperature` to `true`, `Temperature` to `75.0`, and `Air Quality` to `-0.25`. You could also set `Sanity` to `0.1` for regular campfires (since they're meant to be cozy) and `-0.1` for soul campfires (since that's the value for Soul Sand).

Hope this helps!
