### ISSUE TITLE
Request: hide shadow/fox campfire if dont have netherlicious

### ISSUE THREAD

**Issue by huihiuhuai** [connor135246/Campfire-Backport#38]

**Comment by Roadhog360** [comment]
Why hide? Why even register them at all? Seems like wasted IDs.

**Comment by connor135246** [comment]
> Why hide? Why even register them at all?

I guess so that any placed campfires won't be deleted from the world if you decide to remove Netherlicious? I admit it's a pretty minor use case.

> Seems like wasted IDs.

I've never had to use one, but aren't there mods that extend the maximum IDs?

**Comment by Roadhog360** [comment]
Yeah but by removing Netherlicious you are already destroying your entire Nether, it's expected that removing content mods causes block loss.

Yeah there are but they aren't always compatible. Imo it's good practice to be mindful of the IDs that are taken up regardless of if ID extenders exist

**Comment by connor135246** [comment]
Done in v1.11.1

**Comment by Roadhog360** [comment]
Yo, thanks for taking my addendum to the suggestion into account.

Just curious, what is your missing mapping code actually supposed to be doing?

**Comment by connor135246** [comment]
When Netherlicious isn't installed, the foxfire/shadow campfires can be still be enabled with the Enable Extra Campfires config option. 
If the client has Enable Extra Campfires turned off and tries to join a server that has Enable Extra Campfires turned on, the client will be unable to connect because it's missing the foxfire/shadow campfire blocks. The disconnect message that appears on screen is just "Fatally missing blocks/items" which isn't very helpful. So I added that missing mapping check which just puts a message in the console telling the user to turn on Enable Extra Campfires and restart minecraft.
The message will also appear in the console if the client tries to open a local world that was previously opened with Enable Extra Campfires turned on (or a world that was previously opened in v1.11, since foxfire/shadow campfires were always registered in that version).
